name: frontend_format

on: [ push ]

defaults:
  run:
    working-directory: frontend

permissions:
  contents: write

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - uses: creyD/prettier_action@v4.3
        with:
          prettier_options: "-w --cache --plugin-search-dir=. ."
          commit_message: "ci: format code"